name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # ✅ Important! Needed to publish releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Build project
        run: npm run build

      - name: Archive dist folder
        run: |
          mkdir -p release
          zip -r release/git-bash-dist.zip dist

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: release/git-bash-dist.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
